FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y libpam0g-dev libssl-dev zlib1g-dev pkg-config xxd cmake \
    libgtest-dev libgmock-dev ninja-build python3 autoconf-archive autoconf \
    build-essential git libsystemd-dev systemd libtinyxml2-dev python3-wheel python3-pip \
    python3-yaml python3-mako python3-inflection python3-setuptools lighttpd meson python2.7
RUN pip3 install meson==0.57.2
